name: gradlew test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Gradle
      run: ./gradlew test
    - name: Stash reports
      run: |
        mv build/reports $HOME
    - name: Checkout gh-actions-builds branch
      uses: actions/checkout@v1
      with:
        ref: gh-actions-builds
    - name: Commit reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name = "GitHub Action"
        mv $HOME/reports $(pwd)
        git add reports
        git commit -m "Add changes"
    - name: Push reports
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: gh-actions-builds
        force: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
