name: gradlew test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Test with Gradle
      run: ./gradlew test
    - name: Coverage tests
      run: ./gradlew jacocoTestReport
    - name: Mutation tests
      run: ./gradlew pitest
    - name: Stash reports
      run: |
        mkdir $HOME/reports
        mv build/reports/tests build/reports/jacoco $HOME/reports
        mkdir $HOME/reports/pitest
        mv build/reports/pitest/*/* $HOME/reports/pitest
    - name: Checkout gh-actions-builds branch
      uses: actions/checkout@v1
      with:
        ref: gh-pages
    - name: Commit reports
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name = "GitHub Action"
        rm -rf reports
        mv $HOME/reports $(pwd)
        git add reports
        git commit -m "Add changes"
    - name: Push reports
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: gh-pages
        force: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
